version: '3'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterchef2020
      POSTGRES_DB: finedining_db
    volumes:
      - db:/var/lib/postgresql
volumes:
  db:
