spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/finedining_db"
    username: "postgres"
    password: "masterchef2020"
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    generate-ddl: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  flyway:
    url: "jdbc:postgresql://localhost:5432/finedining_db"
    user: "postgres"
    password: "masterchef2020"
    locations: "classpath:db/migration"
    enabled: true
    sql-migration-prefix: "V"

com.school.finediningserver:
  jwtSecret: "finediningSecretKey"
  jwtExpirationMs: 86400000

